# Generated by Django 3.0.7 on 2020-10-13 16:41

from django.db import migrations, models
import home.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('url_playstore', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='video/%y', validators=[home.validators.file_size])),
            ],
        ),
    ]
